# Travis CI Java documentation can be found in:
# https://docs.travis-ci.com/user/languages/java/

# This enables the 'defaults' to test java applications:
language: java

# We can specify a list of JDKs to be used for testing
# A list of available JDKs in Trusty can be seed in:
# https://docs.travis-ci.com/user/reference/trusty/#jvm-clojure-groovy-java-scala-images
jdk:
 - oraclejdk11

env:
  - MAVEN_VERSION=3.3.9

addons:
 sonarcloud:
  organization: "sonarcloud_organization_key" # the key of the org you chose at step #3
  token:
   secure: "*********" # encrypted value of your token
script:
 # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
 - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=myorg_myrepo

# script:
# - bundle exec rake test

# Each job in Travis CI has several steps:
# https://docs.travis-ci.com/user/job-lifecycle/
# The 'language: java' directive sets up sane defaults to test common java applications
# We use the defaults for installing dependencies, compiling and testing maven applications
# In our case it will be 'mvn install' followed by 'mvn test'
# mvn install and mvn test get executed automatically since we have a .pom file
